Repository DeveloperAcademy-POSTECH/MTD-Ahttiary, pull requests merged in 2022-10, with the labels that each got.

#55 [FEAT] 노트 작성 페이지 플로우 변경
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/Models/Comment.swift
  Ahttiary/Models/Emotion.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: 🔧 feature

#56 [Feat, Refactor] 노트 작성 관련 코드의 구조 개선, 인지왜곡 페이지 다시 추가, 아띠 코멘트 업데이트
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/Models/Comment.swift
  Ahttiary/ViewModels/MainViewManager.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/LastPageView.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: :recycle: refactor, 🔧 feature

#63 [Feat] 온보딩 페이지 구현
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/Ahtty/Onboarding_1.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/Onboarding_1.imageset/제목_없는_아트워크 5.png
  Ahttiary/Assets.xcassets/Ahtty/Onboarding_2.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/Onboarding_2.imageset/제목_없는_아트워크 6.png
  Ahttiary/Assets.xcassets/Ahtty/Onboarding_3.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/Onboarding_3.imageset/Onboarding_3.png
  Ahttiary/Extensions/ScreenSize.swift
  Ahttiary/Views/ContentView.swift
  Ahttiary/Views/Onboarding/OnboardingPageView.swift
  Ahttiary/Views/Onboarding/OnboardingTabView.swift
Labels: ✨ UI, 🔧 feature
