Repository DeveloperAcademy-POSTECH/MTD-Ahttiary, pull requests merged in 2022-08, with the labels that each got.

#1 [Feat] Basic git setting
  .gitattributes
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/--add-feature.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/auto_assign.yml
  README.md
Labels: enhancement

#2 [Feat] Main 기본 세팅
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/AhttiaryApp.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/Views/CalendarView.swift
  Ahttiary/Views/MainView.swift
Labels: enhancement

#3 Feat: 노트 작성 페이지 뷰 만들기 + 연관된 Class, Extension 추가
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/AhttyWriter.imageset/Contents.json
  Ahttiary/Assets.xcassets/AhttyWriter.imageset/Image.png
  Ahttiary/Views/Color+Extensions.swift
  Ahttiary/Views/DateFormatter+Extensions.swift
  Ahttiary/Views/NoteManager.swift
  Ahttiary/Views/ScreenSize.swift
  Ahttiary/Views/WriteNoteView.swift
Labels: enhancement

#5 Feat[#4]: 프로토타입대로 다이어리 작성 단계 구현
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Views/CheckPageView.swift
  Ahttiary/Views/EndPageView.swift
  Ahttiary/Views/NoteManager.swift
  Ahttiary/Views/WriteNoteView.swift
  Ahttiary/Views/WritePageView.swift
Labels: enhancement

#6 Feat[#7] 캘린더 기본세팅 구현
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Extensions/Text.swift
  Ahttiary/Models/MonthStruct.swift
  Ahttiary/ViewModels/CalendarViewModel.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/ViewModels/ViewModel.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CalendarView.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/Calendar/DateGridView.swift
Labels: enhancement

#11 [Feat] 캘린더 UI 개선 및 Swipe gesture 적용
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/Colors/Contents.json
  Ahttiary/Assets.xcassets/Colors/ahttyPink.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/ahttyYellow.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/background.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/carrot.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/carrotGreen.colorset/Contents.json
  Ahttiary/Extensions/Color.swift
  Ahttiary/Extensions/Text.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/MainView.swift
Labels: ✨UI, 🔧Feature

#12 Refactor[#10]: 파일 구조 개선
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/AhttiaryApp.swift
  Ahttiary/Assets.xcassets/Colors/Contents.json
  Ahttiary/Assets.xcassets/Colors/ahttyPink.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/ahttyYellow.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/background.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/carrot.colorset/Contents.json
  Ahttiary/Assets.xcassets/Colors/carrotGreen.colorset/Contents.json
  Ahttiary/Extensions/Color.swift
  Ahttiary/Extensions/DateFormatter.swift
  Ahttiary/Extensions/ScreenSize.swift
  Ahttiary/Extensions/Text.swift
  Ahttiary/Models/MonthStruct.swift
  Ahttiary/ViewModels/CalendarViewModel.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/ViewModels/ViewModel.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CalendarView.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/Color+Extensions.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/CheckPageView.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: :recycle: refactor

#19 [HOTFIX] feature/writing 브랜치의 변경 내역을 feature/main 브랜치로 이동
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/AhttiaryApp.swift
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/NSManagedObject.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/CoreData/PersistentStore.swift
  Ahttiary/Extensions/DateFormatter.swift
  Ahttiary/Extensions/ScreenSize.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Note/CheckPageView.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/TemporaryListView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: :lady_beetle: bug

#20 [Feat] Sync up 2022 08 16
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/AhttiaryApp.swift
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/NSManagedObject.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/CoreData/PersistentStore.swift
  Ahttiary/Extensions/DateFormatter.swift
  Ahttiary/Extensions/ScreenSize.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Note/CheckPageView.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/TemporaryListView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: :lady_beetle: bug, 🔧 feature

#24 Feat[#22]: 행복지수 기록 기능 추가
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/Views/Note/SelectHappinessLevelPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
Labels: 🔧 feature

#25 Feat[#7] CalendarView / CoreData 연결 기본 구조 세팅
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/AhttiaryApp.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/ViewModels/MainViewManager.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/ContentView.swift
  Ahttiary/Views/MainView.swift
Labels: 🔧 feature

#30 feat[#27]: Date 값을 "XXXX년 XX월 XX일" 형태의 String으로 변환하는 함수 추가
  Ahttiary/Extensions/Date.swift
Labels: 🔧 feature

#32 Feat: 감정 선택 페이지에 기능 추가 | 아띠의 질문을 랜덤으로 수정 | 대답이 비어있으면 다음 버튼을 비활성화
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/Models/Comment.swift
  Ahttiary/Models/Emotion.swift
  Ahttiary/ViewModels/MainViewManager.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/SelectHappinessLevelPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
Labels: 🔧 feature

#33 Feat[#7] 캘린더 UI 개선
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/Colors/background.colorset/Contents.json
  Ahttiary/CoreData/Ahttiary.xcdatamodeld/Ahttiary.xcdatamodel/contents
  Ahttiary/CoreData/DraftNote.swift
  Ahttiary/CoreData/Note.swift
  Ahttiary/Extensions/Date.swift
  Ahttiary/Extensions/Text.swift
  Ahttiary/Fonts/Font.swift
  Ahttiary/Fonts/Poppins-Regular.ttf
  Ahttiary/Info.plist
  Ahttiary/Models/Comment.swift
  Ahttiary/Models/Emotion.swift
  Ahttiary/ViewModels/MainViewManager.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/CustomNavigationBar.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/CheckPageView.swift
  Ahttiary/Views/Note/CustomButton.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/TemporaryListView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: :recycle: refactor, 🔧 feature

#34 Feat[#26]: 인지왜곡 선택 페이지 로직 구현
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/Colors/background.colorset/Contents.json
  Ahttiary/CoreData/Note.swift
  Ahttiary/Extensions/ScreenSize.swift
  Ahttiary/Extensions/Text.swift
  Ahttiary/Fonts/Font.swift
  Ahttiary/Fonts/Poppins-Regular.ttf
  Ahttiary/Info.plist
  Ahttiary/Models/CognitiveDistortion.swift
  Ahttiary/ViewModels/DistortionPageManager.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/CustomNavigationBar.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/CognitiveDistortionCard.swift
  Ahttiary/Views/Note/CognitiveDistortionCell.swift
  Ahttiary/Views/Note/CustomButton.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: 🔧 feature

#36 [Feat] Develop UI of Cognitive Distortion Selection process
  Ahttiary/Models/CognitiveDistortion.swift
  Ahttiary/Views/Note/CognitiveDistortionCard.swift
  Ahttiary/Views/Note/CognitiveDistortionCell.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
Labels: :recycle: refactor, 🔧 feature

#37 Feat[#7] 캘린더 - 코어데이터 연결 로직
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Extensions/Date.swift
  Ahttiary/Extensions/ScreenSize.swift
  Ahttiary/Models/CognitiveDistortion.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/ViewModels/DistortionPageManager.swift
  Ahttiary/ViewModels/MainViewManager.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/ContentView.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/CognitiveDistortionCard.swift
  Ahttiary/Views/Note/CognitiveDistortionCell.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: :recycle: refactor, 🔧 feature

#38 [Feat] Set carrot image on the day with note CoreData
  Ahttiary/Assets.xcassets/Ahtty/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/bbaeggomAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/bbaeggomAhtty.imageset/bbaeggomAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/helloAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/helloAhtty.imageset/helloAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/noteAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/noteAhtty.imageset/noteAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/questionAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/questionAhtty.imageset/questionAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/selectinAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/selectinAhtty.imageset/selectinAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/teaAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/teaAhtty.imageset/teaAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/thinkinAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/thinkinAhtty.imageset/thinkinAhtty.png
  Ahttiary/Assets.xcassets/ahttyHello.imageset/ahttyHello.png
  Ahttiary/Assets.xcassets/carrot.imageset/Contents.json
  Ahttiary/Assets.xcassets/carrot.imageset/Vector.png
  Ahttiary/Assets.xcassets/emoji/Contents.json
  Ahttiary/Assets.xcassets/emoji/angry.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/angry.imageset/angry.png
  Ahttiary/Assets.xcassets/emoji/happy.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/happy.imageset/happy.png
  Ahttiary/Assets.xcassets/emoji/irritated.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/irritated.imageset/irritated.png
  Ahttiary/Assets.xcassets/emoji/sad.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/sad.imageset/sad.png
  Ahttiary/Assets.xcassets/emoji/satisfied.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/satisfied.imageset/satisfied.png
  Ahttiary/Assets.xcassets/emoji/scared.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/scared.imageset/scared.png
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/CognitiveDistortionCell.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: 🔧 feature

#40 Feat: 노트 작성 페이지 스와이프 제스쳐 비활성화 | 노트 작성 페이지 UI/UX 개선
  Ahttiary/Assets.xcassets/Ahtty/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/bbaeggomAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/bbaeggomAhtty.imageset/bbaeggomAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/helloAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/helloAhtty.imageset/helloAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/noteAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/noteAhtty.imageset/noteAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/questionAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/questionAhtty.imageset/questionAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/selectinAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/selectinAhtty.imageset/selectinAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/teaAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/teaAhtty.imageset/teaAhtty.png
  Ahttiary/Assets.xcassets/Ahtty/thinkinAhtty.imageset/Contents.json
  Ahttiary/Assets.xcassets/Ahtty/thinkinAhtty.imageset/thinkinAhtty.png
  Ahttiary/Assets.xcassets/ahttyHello.imageset/ahttyHello.png
  Ahttiary/Assets.xcassets/carrot.imageset/Contents.json
  Ahttiary/Assets.xcassets/carrot.imageset/Vector.png
  Ahttiary/Assets.xcassets/emoji/Contents.json
  Ahttiary/Assets.xcassets/emoji/angry.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/angry.imageset/angry.png
  Ahttiary/Assets.xcassets/emoji/happy.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/happy.imageset/happy.png
  Ahttiary/Assets.xcassets/emoji/irritated.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/irritated.imageset/irritated.png
  Ahttiary/Assets.xcassets/emoji/sad.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/sad.imageset/sad.png
  Ahttiary/Assets.xcassets/emoji/satisfied.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/satisfied.imageset/satisfied.png
  Ahttiary/Assets.xcassets/emoji/scared.imageset/Contents.json
  Ahttiary/Assets.xcassets/emoji/scared.imageset/scared.png
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/CognitiveDistortionCard.swift
  Ahttiary/Views/Note/CognitiveDistortionCell.swift
  Ahttiary/Views/Note/EndPageView.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: ✨ UI, 🔧 feature

#43 Feat: 앱 아이콘, 앱 이름
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/AppIcon.appiconset/100.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/1024.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/114.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/120.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/144.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/152.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/167.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/180.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/20.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/29.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/40.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/50.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/57.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/58.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/60.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/72.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/76.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/80.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/87.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ahttiary/Views/Note/CognitiveDistortionCard.swift
Labels: 🔧 feature

#45 Feat[#7]: 캘린더 전환 시 트랜지션 적용
  Ahttiary/Views/Calendar/DateGridView.swift
Labels: 🔧 feature

#47 Fix: 키보드 관련 UX 개선 + 뒤로가기 버튼을 눌러도 변경 내역을 저장하도록 변경
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Info.plist
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/Note/ChangePageButton.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  Ahttiary/Views/Note/WritePageView.swift
  아띠어리.entitlements
Labels: :lady_beetle: bug, ✨ UI

#48 Fix[#7]: 캘린더 날짜 선택 버그 수정
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Info.plist
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  아띠어리.entitlements
Labels: :lady_beetle: bug

#49 Feat: feature/main -> develop
  Ahttiary.xcodeproj/project.pbxproj
  Ahttiary/Assets.xcassets/AppIcon.appiconset/100.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/1024.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/114.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/120.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/144.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/152.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/167.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/180.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/20.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/29.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/40.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/50.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/57.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/58.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/60.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/72.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/76.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/80.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/87.png
  Ahttiary/Assets.xcassets/AppIcon.appiconset/Contents.json
  Ahttiary/Assets.xcassets/Colors/cardBackground.colorset/Contents.json
  Ahttiary/Assets.xcassets/carrot.imageset/Contents.json
  Ahttiary/Assets.xcassets/carrot.imageset/Frame.png
  Ahttiary/Assets.xcassets/carrot.imageset/Vector.png
  Ahttiary/Extensions/Color.swift
  Ahttiary/Info.plist
  Ahttiary/Models/CognitiveDistortion.swift
  Ahttiary/Models/Comment.swift
  Ahttiary/Models/Emotion.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/Views/Calendar/DateGridView.swift
  Ahttiary/Views/Note/CognitiveDistortionCard.swift
  Ahttiary/Views/Note/CognitiveDistortionCell.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WriteNoteView.swift
  아띠어리.entitlements
Labels: 🔧 feature

#52 Style: UI 개선
  Ahttiary/Assets.xcassets/Colors/fontGray.colorset/Contents.json
  Ahttiary/Extensions/Color.swift
  Ahttiary/Fonts/Font.swift
  Ahttiary/ViewModels/DateViewModel.swift
  Ahttiary/ViewModels/NoteManager.swift
  Ahttiary/Views/Calendar/CalendarCell.swift
  Ahttiary/Views/Calendar/CalendarView.swift
  Ahttiary/Views/Calendar/CurrentMonthView.swift
  Ahttiary/Views/MainView.swift
  Ahttiary/Views/Note/SelectCognitiveDistortionPageView.swift
  Ahttiary/Views/Note/SelectEmotionPageView.swift
  Ahttiary/Views/Note/WritePageView.swift
Labels: ✨ UI, 🔧 feature
